import type { TankClassId, TankClassDef } from './types';

export const TANK_CLASSES: Record<TankClassId, TankClassDef> = {
  soldier: {
    id: 'soldier',
    name: 'Soldier',
    description: 'Well-rounded standard tank. No frills, no weaknesses.',
    maxHp: 100,
    moveDistance: 60,
    explosionRadiusMultiplier: 1,
    directHitDamageMultiplier: 1,
    splashRadiusMultiplier: 1,
    terrainDamageMultiplier: 1,
    specialAbility: 'none',
    barrelLength: 28,
    bodyWidth: 40,
    bodyHeight: 20,
    color: '#6B8E23',
    darkColor: '#4A6318',
  },
  bertha: {
    id: 'bertha',
    name: 'Bertha',
    description: 'Heavy mortar with massive explosions. Slow but devastating.',
    maxHp: 130,
    moveDistance: 40,
    explosionRadiusMultiplier: 1.5,
    directHitDamageMultiplier: 1,
    splashRadiusMultiplier: 1.5,
    terrainDamageMultiplier: 1.5,
    specialAbility: 'big_explosion',
    barrelLength: 32,
    bodyWidth: 50,
    bodyHeight: 24,
    color: '#8B6914',
    darkColor: '#5C4A0E',
  },
  jackal: {
    id: 'jackal',
    name: 'Jackal',
    description: 'Fast and agile. Shot splits into 3 at apex.',
    maxHp: 80,
    moveDistance: 90,
    explosionRadiusMultiplier: 0.7,
    directHitDamageMultiplier: 0.7,
    splashRadiusMultiplier: 0.7,
    terrainDamageMultiplier: 0.7,
    specialAbility: 'split_shot',
    barrelLength: 24,
    bodyWidth: 36,
    bodyHeight: 16,
    color: '#DAA520',
    darkColor: '#B8860B',
  },
  longbow: {
    id: 'longbow',
    name: 'Longbow',
    description: 'Precision sniper. 2x direct hit damage, tiny splash.',
    maxHp: 85,
    moveDistance: 50,
    explosionRadiusMultiplier: 0.6,
    directHitDamageMultiplier: 2,
    splashRadiusMultiplier: 0.5,
    terrainDamageMultiplier: 0.6,
    specialAbility: 'precision',
    barrelLength: 36,
    bodyWidth: 38,
    bodyHeight: 18,
    color: '#4682B4',
    darkColor: '#2C5F85',
  },
  trickshot: {
    id: 'trickshot',
    name: 'Trickshot',
    description: 'Projectile bounces off terrain once. Master the angles.',
    maxHp: 90,
    moveDistance: 60,
    explosionRadiusMultiplier: 1,
    directHitDamageMultiplier: 1,
    splashRadiusMultiplier: 1,
    terrainDamageMultiplier: 1,
    specialAbility: 'bounce',
    barrelLength: 26,
    bodyWidth: 40,
    bodyHeight: 20,
    color: '#9370DB',
    darkColor: '#6A4FB0',
  },
  aegis: {
    id: 'aegis',
    name: 'Aegis',
    description: 'Defensive fortress. Alt-fire deploys a terrain wall.',
    maxHp: 110,
    moveDistance: 50,
    explosionRadiusMultiplier: 1,
    directHitDamageMultiplier: 1,
    splashRadiusMultiplier: 1,
    terrainDamageMultiplier: 1,
    specialAbility: 'wall',
    barrelLength: 28,
    bodyWidth: 44,
    bodyHeight: 22,
    color: '#20B2AA',
    darkColor: '#147A75',
  },
};

export const TANK_CLASS_IDS: TankClassId[] = ['soldier', 'bertha', 'jackal', 'longbow', 'trickshot', 'aegis'];
